version: 2.1

parameters:
  environment:
    type: string
    default: "production"  # Default value if no value is passed

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Set environment variable
          command: |
            echo "export ENVIRONMENT1=saurabh" >> $BASH_ENV
      - run:
          name: Verify environment variable
          command: |
            echo "Current environment1 is $ENVIRONMENT1"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
