version: 2.1

parameters:
  environment:
    type: string
    default: "production"  # Default value if no value is passed

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    ENVIRONMENT:
      IMAGETAG: << pipeline.parameters.environment >>
    steps:
      - run:
          name: Verify environment variable
          command: |
            echo "Current environment1 is $ENVIRONMENT"

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
